/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import robot.ev3.dls.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see robot.ev3.dls.DlsPackage
 * @generated
 */
public class DlsAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static DlsPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DlsAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = DlsPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DlsSwitch<Adapter> modelSwitch =
    new DlsSwitch<Adapter>()
    {
      @Override
      public Adapter caseMission(Mission object)
      {
        return createMissionAdapter();
      }
      @Override
      public Adapter caseBehavior(Behavior object)
      {
        return createBehaviorAdapter();
      }
      @Override
      public Adapter caseTakeControl(TakeControl object)
      {
        return createTakeControlAdapter();
      }
      @Override
      public Adapter caseMeasurableConditions(MeasurableConditions object)
      {
        return createMeasurableConditionsAdapter();
      }
      @Override
      public Adapter caseMeasurableCondition(MeasurableCondition object)
      {
        return createMeasurableConditionAdapter();
      }
      @Override
      public Adapter caseIntExpression(IntExpression object)
      {
        return createIntExpressionAdapter();
      }
      @Override
      public Adapter caseExpressionMinus(ExpressionMinus object)
      {
        return createExpressionMinusAdapter();
      }
      @Override
      public Adapter caseExpressionPlus(ExpressionPlus object)
      {
        return createExpressionPlusAdapter();
      }
      @Override
      public Adapter caseExpressionBracket(ExpressionBracket object)
      {
        return createExpressionBracketAdapter();
      }
      @Override
      public Adapter caseExpressionConstantInt(ExpressionConstantInt object)
      {
        return createExpressionConstantIntAdapter();
      }
      @Override
      public Adapter caseBooleanExpression(BooleanExpression object)
      {
        return createBooleanExpressionAdapter();
      }
      @Override
      public Adapter caseNotExpression(NotExpression object)
      {
        return createNotExpressionAdapter();
      }
      @Override
      public Adapter caseBooleanExpressionBracket(BooleanExpressionBracket object)
      {
        return createBooleanExpressionBracketAdapter();
      }
      @Override
      public Adapter caseBooleanExpressionConstant(BooleanExpressionConstant object)
      {
        return createBooleanExpressionConstantAdapter();
      }
      @Override
      public Adapter caseExpressionAddition(ExpressionAddition object)
      {
        return createExpressionAdditionAdapter();
      }
      @Override
      public Adapter caseExpressionSubtraction(ExpressionSubtraction object)
      {
        return createExpressionSubtractionAdapter();
      }
      @Override
      public Adapter caseExpressionMultiply(ExpressionMultiply object)
      {
        return createExpressionMultiplyAdapter();
      }
      @Override
      public Adapter caseExpressionDivision(ExpressionDivision object)
      {
        return createExpressionDivisionAdapter();
      }
      @Override
      public Adapter caseExpressionMaximum(ExpressionMaximum object)
      {
        return createExpressionMaximumAdapter();
      }
      @Override
      public Adapter caseExpressionMinimum(ExpressionMinimum object)
      {
        return createExpressionMinimumAdapter();
      }
      @Override
      public Adapter caseExpressionModulo(ExpressionModulo object)
      {
        return createExpressionModuloAdapter();
      }
      @Override
      public Adapter caseExpressionPower(ExpressionPower object)
      {
        return createExpressionPowerAdapter();
      }
      @Override
      public Adapter caseExpressionBinOp(ExpressionBinOp object)
      {
        return createExpressionBinOpAdapter();
      }
      @Override
      public Adapter caseExpressionCompOp(ExpressionCompOp object)
      {
        return createExpressionCompOpAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.Mission <em>Mission</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.Mission
   * @generated
   */
  public Adapter createMissionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.Behavior <em>Behavior</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.Behavior
   * @generated
   */
  public Adapter createBehaviorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.TakeControl <em>Take Control</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.TakeControl
   * @generated
   */
  public Adapter createTakeControlAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.MeasurableConditions <em>Measurable Conditions</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.MeasurableConditions
   * @generated
   */
  public Adapter createMeasurableConditionsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.MeasurableCondition <em>Measurable Condition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.MeasurableCondition
   * @generated
   */
  public Adapter createMeasurableConditionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.IntExpression
   * @generated
   */
  public Adapter createIntExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionMinus <em>Expression Minus</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionMinus
   * @generated
   */
  public Adapter createExpressionMinusAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionPlus <em>Expression Plus</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionPlus
   * @generated
   */
  public Adapter createExpressionPlusAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionBracket <em>Expression Bracket</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionBracket
   * @generated
   */
  public Adapter createExpressionBracketAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionConstantInt <em>Expression Constant Int</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionConstantInt
   * @generated
   */
  public Adapter createExpressionConstantIntAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.BooleanExpression <em>Boolean Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.BooleanExpression
   * @generated
   */
  public Adapter createBooleanExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.NotExpression <em>Not Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.NotExpression
   * @generated
   */
  public Adapter createNotExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.BooleanExpressionBracket <em>Boolean Expression Bracket</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.BooleanExpressionBracket
   * @generated
   */
  public Adapter createBooleanExpressionBracketAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.BooleanExpressionConstant <em>Boolean Expression Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.BooleanExpressionConstant
   * @generated
   */
  public Adapter createBooleanExpressionConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionAddition <em>Expression Addition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionAddition
   * @generated
   */
  public Adapter createExpressionAdditionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionSubtraction <em>Expression Subtraction</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionSubtraction
   * @generated
   */
  public Adapter createExpressionSubtractionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionMultiply <em>Expression Multiply</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionMultiply
   * @generated
   */
  public Adapter createExpressionMultiplyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionDivision <em>Expression Division</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionDivision
   * @generated
   */
  public Adapter createExpressionDivisionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionMaximum <em>Expression Maximum</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionMaximum
   * @generated
   */
  public Adapter createExpressionMaximumAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionMinimum <em>Expression Minimum</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionMinimum
   * @generated
   */
  public Adapter createExpressionMinimumAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionModulo <em>Expression Modulo</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionModulo
   * @generated
   */
  public Adapter createExpressionModuloAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionPower <em>Expression Power</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionPower
   * @generated
   */
  public Adapter createExpressionPowerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionBinOp <em>Expression Bin Op</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionBinOp
   * @generated
   */
  public Adapter createExpressionBinOpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link robot.ev3.dls.ExpressionCompOp <em>Expression Comp Op</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see robot.ev3.dls.ExpressionCompOp
   * @generated
   */
  public Adapter createExpressionCompOpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //DlsAdapterFactory
