/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ignorables</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.ev3.dsl.Ignorables#getAVOID_OBJECTS <em>AVOID OBJECTS</em>}</li>
 * </ul>
 *
 * @see robot.ev3.dsl.DslPackage#getIgnorables()
 * @model
 * @generated
 */
public interface Ignorables extends EObject
{
  /**
   * Returns the value of the '<em><b>AVOID OBJECTS</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>AVOID OBJECTS</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>AVOID OBJECTS</em>' attribute.
   * @see #setAVOID_OBJECTS(String)
   * @see robot.ev3.dsl.DslPackage#getIgnorables_AVOID_OBJECTS()
   * @model
   * @generated
   */
  String getAVOID_OBJECTS();

  /**
   * Sets the value of the '{@link robot.ev3.dsl.Ignorables#getAVOID_OBJECTS <em>AVOID OBJECTS</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>AVOID OBJECTS</em>' attribute.
   * @see #getAVOID_OBJECTS()
   * @generated
   */
  void setAVOID_OBJECTS(String value);

} // Ignorables
