/*
 * generated by Xtext 2.10.0
 */
package robot.ev3.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import robot.ev3.dls.ColorSensor;
import robot.ev3.dls.DlsPackage;
import robot.ev3.dls.Mission;
import robot.ev3.dls.Task;
import robot.ev3.dls.TouchSensor;
import robot.ev3.dls.UltrasonicSensor;
import robot.ev3.services.DslGrammarAccess;

@SuppressWarnings("all")
public class DslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DlsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DlsPackage.COLOR_SENSOR:
				sequence_ColorSensor(context, (ColorSensor) semanticObject); 
				return; 
			case DlsPackage.MISSION:
				sequence_Mission(context, (Mission) semanticObject); 
				return; 
			case DlsPackage.TASK:
				sequence_Task(context, (Task) semanticObject); 
				return; 
			case DlsPackage.TOUCH_SENSOR:
				sequence_TouchSensor(context, (TouchSensor) semanticObject); 
				return; 
			case DlsPackage.ULTRASONIC_SENSOR:
				sequence_UltrasonicSensor(context, (UltrasonicSensor) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     SensorType returns ColorSensor
	 *     ColorSensor returns ColorSensor
	 *
	 * Constraint:
	 *     key=Colors
	 */
	protected void sequence_ColorSensor(ISerializationContext context, ColorSensor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DlsPackage.Literals.COLOR_SENSOR__KEY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DlsPackage.Literals.COLOR_SENSOR__KEY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getColorSensorAccess().getKeyColorsEnumRuleCall_4_0(), semanticObject.getKey());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Mission returns Mission
	 *
	 * Constraint:
	 *     tasks+=Task+
	 */
	protected void sequence_Mission(ISerializationContext context, Mission semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Task returns Task
	 *
	 * Constraint:
	 *     (name=ID sensor=SensorType action=Actions)
	 */
	protected void sequence_Task(ISerializationContext context, Task semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DlsPackage.Literals.TASK__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DlsPackage.Literals.TASK__NAME));
			if (transientValues.isValueTransient(semanticObject, DlsPackage.Literals.TASK__SENSOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DlsPackage.Literals.TASK__SENSOR));
			if (transientValues.isValueTransient(semanticObject, DlsPackage.Literals.TASK__ACTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DlsPackage.Literals.TASK__ACTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTaskAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTaskAccess().getSensorSensorTypeParserRuleCall_3_0(), semanticObject.getSensor());
		feeder.accept(grammarAccess.getTaskAccess().getActionActionsEnumRuleCall_5_0(), semanticObject.getAction());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SensorType returns TouchSensor
	 *     TouchSensor returns TouchSensor
	 *
	 * Constraint:
	 *     key=TouchSensorSides
	 */
	protected void sequence_TouchSensor(ISerializationContext context, TouchSensor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DlsPackage.Literals.TOUCH_SENSOR__KEY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DlsPackage.Literals.TOUCH_SENSOR__KEY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTouchSensorAccess().getKeyTouchSensorSidesEnumRuleCall_3_0(), semanticObject.getKey());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SensorType returns UltrasonicSensor
	 *     UltrasonicSensor returns UltrasonicSensor
	 *
	 * Constraint:
	 *     (comparator=CompareOperator distance=DECIMAL)
	 */
	protected void sequence_UltrasonicSensor(ISerializationContext context, UltrasonicSensor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DlsPackage.Literals.ULTRASONIC_SENSOR__COMPARATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DlsPackage.Literals.ULTRASONIC_SENSOR__COMPARATOR));
			if (transientValues.isValueTransient(semanticObject, DlsPackage.Literals.ULTRASONIC_SENSOR__DISTANCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DlsPackage.Literals.ULTRASONIC_SENSOR__DISTANCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUltrasonicSensorAccess().getComparatorCompareOperatorEnumRuleCall_3_0(), semanticObject.getComparator());
		feeder.accept(grammarAccess.getUltrasonicSensorAccess().getDistanceDECIMALTerminalRuleCall_4_0(), semanticObject.getDistance());
		feeder.finish();
	}
	
	
}
