/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import robot.ev3.dls.DlsPackage;
import robot.ev3.dls.SensorType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sensor Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SensorTypeImpl extends MinimalEObjectImpl.Container implements SensorType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SensorTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DlsPackage.Literals.SENSOR_TYPE;
  }

} //SensorTypeImpl
