/*
 * generated by Xtext 2.10.0
 */
package robot.ev3.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import robot.ev3.ui.internal.Ev3Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Ev3Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Ev3Activator.getInstance().getInjector(Ev3Activator.ROBOT_EV3_DSL);
	}
	
}
