/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.ev3.dls.Behavior#getName <em>Name</em>}</li>
 *   <li>{@link robot.ev3.dls.Behavior#getBehaviorType <em>Behavior Type</em>}</li>
 *   <li>{@link robot.ev3.dls.Behavior#getPrio <em>Prio</em>}</li>
 *   <li>{@link robot.ev3.dls.Behavior#getControl <em>Control</em>}</li>
 *   <li>{@link robot.ev3.dls.Behavior#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see robot.ev3.dls.DlsPackage#getBehavior()
 * @model
 * @generated
 */
public interface Behavior extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see robot.ev3.dls.DlsPackage#getBehavior_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link robot.ev3.dls.Behavior#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Behavior Type</b></em>' attribute.
   * The literals are from the enumeration {@link robot.ev3.dls.BehaviorTypes}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Behavior Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behavior Type</em>' attribute.
   * @see robot.ev3.dls.BehaviorTypes
   * @see #setBehaviorType(BehaviorTypes)
   * @see robot.ev3.dls.DlsPackage#getBehavior_BehaviorType()
   * @model
   * @generated
   */
  BehaviorTypes getBehaviorType();

  /**
   * Sets the value of the '{@link robot.ev3.dls.Behavior#getBehaviorType <em>Behavior Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Behavior Type</em>' attribute.
   * @see robot.ev3.dls.BehaviorTypes
   * @see #getBehaviorType()
   * @generated
   */
  void setBehaviorType(BehaviorTypes value);

  /**
   * Returns the value of the '<em><b>Prio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prio</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prio</em>' attribute.
   * @see #setPrio(int)
   * @see robot.ev3.dls.DlsPackage#getBehavior_Prio()
   * @model
   * @generated
   */
  int getPrio();

  /**
   * Sets the value of the '{@link robot.ev3.dls.Behavior#getPrio <em>Prio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prio</em>' attribute.
   * @see #getPrio()
   * @generated
   */
  void setPrio(int value);

  /**
   * Returns the value of the '<em><b>Control</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Control</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Control</em>' containment reference.
   * @see #setControl(TakeControl)
   * @see robot.ev3.dls.DlsPackage#getBehavior_Control()
   * @model containment="true"
   * @generated
   */
  TakeControl getControl();

  /**
   * Sets the value of the '{@link robot.ev3.dls.Behavior#getControl <em>Control</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Control</em>' containment reference.
   * @see #getControl()
   * @generated
   */
  void setControl(TakeControl value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' attribute.
   * The literals are from the enumeration {@link robot.ev3.dls.Actions}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actions</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' attribute.
   * @see robot.ev3.dls.Actions
   * @see #setActions(Actions)
   * @see robot.ev3.dls.DlsPackage#getBehavior_Actions()
   * @model
   * @generated
   */
  Actions getActions();

  /**
   * Sets the value of the '{@link robot.ev3.dls.Behavior#getActions <em>Actions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actions</em>' attribute.
   * @see robot.ev3.dls.Actions
   * @see #getActions()
   * @generated
   */
  void setActions(Actions value);

} // Behavior
