/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see robot.ev3.dls.DlsPackage
 * @generated
 */
public interface DlsFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DlsFactory eINSTANCE = robot.ev3.dls.impl.DlsFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Mission</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mission</em>'.
   * @generated
   */
  Mission createMission();

  /**
   * Returns a new object of class '<em>Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task</em>'.
   * @generated
   */
  Task createTask();

  /**
   * Returns a new object of class '<em>Sensor Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor Type</em>'.
   * @generated
   */
  SensorType createSensorType();

  /**
   * Returns a new object of class '<em>Color Sensor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Color Sensor</em>'.
   * @generated
   */
  ColorSensor createColorSensor();

  /**
   * Returns a new object of class '<em>Touch Sensor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Touch Sensor</em>'.
   * @generated
   */
  TouchSensor createTouchSensor();

  /**
   * Returns a new object of class '<em>Ultrasonic Sensor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ultrasonic Sensor</em>'.
   * @generated
   */
  UltrasonicSensor createUltrasonicSensor();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DlsPackage getDlsPackage();

} //DlsFactory
