/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see robot.ev3.dls.DlsFactory
 * @model kind="package"
 * @generated
 */
public interface DlsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dls";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ev3.robot/dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dls";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DlsPackage eINSTANCE = robot.ev3.dls.impl.DlsPackageImpl.init();

  /**
   * The meta object id for the '{@link robot.ev3.dls.impl.MissionImpl <em>Mission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.impl.MissionImpl
   * @see robot.ev3.dls.impl.DlsPackageImpl#getMission()
   * @generated
   */
  int MISSION = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__TASKS = 0;

  /**
   * The number of structural features of the '<em>Mission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link robot.ev3.dls.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.impl.TaskImpl
   * @see robot.ev3.dls.impl.DlsPackageImpl#getTask()
   * @generated
   */
  int TASK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__SENSOR = 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ACTION = 2;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link robot.ev3.dls.impl.SensorTypeImpl <em>Sensor Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.impl.SensorTypeImpl
   * @see robot.ev3.dls.impl.DlsPackageImpl#getSensorType()
   * @generated
   */
  int SENSOR_TYPE = 2;

  /**
   * The number of structural features of the '<em>Sensor Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link robot.ev3.dls.impl.ColorSensorImpl <em>Color Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.impl.ColorSensorImpl
   * @see robot.ev3.dls.impl.DlsPackageImpl#getColorSensor()
   * @generated
   */
  int COLOR_SENSOR = 3;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENSOR__KEY = SENSOR_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Color Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENSOR_FEATURE_COUNT = SENSOR_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.ev3.dls.impl.TouchSensorImpl <em>Touch Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.impl.TouchSensorImpl
   * @see robot.ev3.dls.impl.DlsPackageImpl#getTouchSensor()
   * @generated
   */
  int TOUCH_SENSOR = 4;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_SENSOR__KEY = SENSOR_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Touch Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_SENSOR_FEATURE_COUNT = SENSOR_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.ev3.dls.impl.UltrasonicSensorImpl <em>Ultrasonic Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.impl.UltrasonicSensorImpl
   * @see robot.ev3.dls.impl.DlsPackageImpl#getUltrasonicSensor()
   * @generated
   */
  int ULTRASONIC_SENSOR = 5;

  /**
   * The feature id for the '<em><b>Comparator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ULTRASONIC_SENSOR__COMPARATOR = SENSOR_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ULTRASONIC_SENSOR__DISTANCE = SENSOR_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ultrasonic Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ULTRASONIC_SENSOR_FEATURE_COUNT = SENSOR_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link robot.ev3.dls.TouchSensorSides <em>Touch Sensor Sides</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.TouchSensorSides
   * @see robot.ev3.dls.impl.DlsPackageImpl#getTouchSensorSides()
   * @generated
   */
  int TOUCH_SENSOR_SIDES = 6;

  /**
   * The meta object id for the '{@link robot.ev3.dls.Actions <em>Actions</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.Actions
   * @see robot.ev3.dls.impl.DlsPackageImpl#getActions()
   * @generated
   */
  int ACTIONS = 7;

  /**
   * The meta object id for the '{@link robot.ev3.dls.Directions <em>Directions</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.Directions
   * @see robot.ev3.dls.impl.DlsPackageImpl#getDirections()
   * @generated
   */
  int DIRECTIONS = 8;

  /**
   * The meta object id for the '{@link robot.ev3.dls.Colors <em>Colors</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.Colors
   * @see robot.ev3.dls.impl.DlsPackageImpl#getColors()
   * @generated
   */
  int COLORS = 9;

  /**
   * The meta object id for the '{@link robot.ev3.dls.CompareOperator <em>Compare Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.ev3.dls.CompareOperator
   * @see robot.ev3.dls.impl.DlsPackageImpl#getCompareOperator()
   * @generated
   */
  int COMPARE_OPERATOR = 10;


  /**
   * Returns the meta object for class '{@link robot.ev3.dls.Mission <em>Mission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mission</em>'.
   * @see robot.ev3.dls.Mission
   * @generated
   */
  EClass getMission();

  /**
   * Returns the meta object for the containment reference list '{@link robot.ev3.dls.Mission#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see robot.ev3.dls.Mission#getTasks()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Tasks();

  /**
   * Returns the meta object for class '{@link robot.ev3.dls.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see robot.ev3.dls.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link robot.ev3.dls.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see robot.ev3.dls.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the containment reference '{@link robot.ev3.dls.Task#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sensor</em>'.
   * @see robot.ev3.dls.Task#getSensor()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Sensor();

  /**
   * Returns the meta object for the attribute '{@link robot.ev3.dls.Task#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see robot.ev3.dls.Task#getAction()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Action();

  /**
   * Returns the meta object for class '{@link robot.ev3.dls.SensorType <em>Sensor Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Type</em>'.
   * @see robot.ev3.dls.SensorType
   * @generated
   */
  EClass getSensorType();

  /**
   * Returns the meta object for class '{@link robot.ev3.dls.ColorSensor <em>Color Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color Sensor</em>'.
   * @see robot.ev3.dls.ColorSensor
   * @generated
   */
  EClass getColorSensor();

  /**
   * Returns the meta object for the attribute '{@link robot.ev3.dls.ColorSensor#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see robot.ev3.dls.ColorSensor#getKey()
   * @see #getColorSensor()
   * @generated
   */
  EAttribute getColorSensor_Key();

  /**
   * Returns the meta object for class '{@link robot.ev3.dls.TouchSensor <em>Touch Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Touch Sensor</em>'.
   * @see robot.ev3.dls.TouchSensor
   * @generated
   */
  EClass getTouchSensor();

  /**
   * Returns the meta object for the attribute '{@link robot.ev3.dls.TouchSensor#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see robot.ev3.dls.TouchSensor#getKey()
   * @see #getTouchSensor()
   * @generated
   */
  EAttribute getTouchSensor_Key();

  /**
   * Returns the meta object for class '{@link robot.ev3.dls.UltrasonicSensor <em>Ultrasonic Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ultrasonic Sensor</em>'.
   * @see robot.ev3.dls.UltrasonicSensor
   * @generated
   */
  EClass getUltrasonicSensor();

  /**
   * Returns the meta object for the attribute '{@link robot.ev3.dls.UltrasonicSensor#getComparator <em>Comparator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparator</em>'.
   * @see robot.ev3.dls.UltrasonicSensor#getComparator()
   * @see #getUltrasonicSensor()
   * @generated
   */
  EAttribute getUltrasonicSensor_Comparator();

  /**
   * Returns the meta object for the attribute '{@link robot.ev3.dls.UltrasonicSensor#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see robot.ev3.dls.UltrasonicSensor#getDistance()
   * @see #getUltrasonicSensor()
   * @generated
   */
  EAttribute getUltrasonicSensor_Distance();

  /**
   * Returns the meta object for enum '{@link robot.ev3.dls.TouchSensorSides <em>Touch Sensor Sides</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Touch Sensor Sides</em>'.
   * @see robot.ev3.dls.TouchSensorSides
   * @generated
   */
  EEnum getTouchSensorSides();

  /**
   * Returns the meta object for enum '{@link robot.ev3.dls.Actions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Actions</em>'.
   * @see robot.ev3.dls.Actions
   * @generated
   */
  EEnum getActions();

  /**
   * Returns the meta object for enum '{@link robot.ev3.dls.Directions <em>Directions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Directions</em>'.
   * @see robot.ev3.dls.Directions
   * @generated
   */
  EEnum getDirections();

  /**
   * Returns the meta object for enum '{@link robot.ev3.dls.Colors <em>Colors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Colors</em>'.
   * @see robot.ev3.dls.Colors
   * @generated
   */
  EEnum getColors();

  /**
   * Returns the meta object for enum '{@link robot.ev3.dls.CompareOperator <em>Compare Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Compare Operator</em>'.
   * @see robot.ev3.dls.CompareOperator
   * @generated
   */
  EEnum getCompareOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DlsFactory getDlsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link robot.ev3.dls.impl.MissionImpl <em>Mission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.impl.MissionImpl
     * @see robot.ev3.dls.impl.DlsPackageImpl#getMission()
     * @generated
     */
    EClass MISSION = eINSTANCE.getMission();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__TASKS = eINSTANCE.getMission_Tasks();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.impl.TaskImpl
     * @see robot.ev3.dls.impl.DlsPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__SENSOR = eINSTANCE.getTask_Sensor();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__ACTION = eINSTANCE.getTask_Action();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.impl.SensorTypeImpl <em>Sensor Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.impl.SensorTypeImpl
     * @see robot.ev3.dls.impl.DlsPackageImpl#getSensorType()
     * @generated
     */
    EClass SENSOR_TYPE = eINSTANCE.getSensorType();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.impl.ColorSensorImpl <em>Color Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.impl.ColorSensorImpl
     * @see robot.ev3.dls.impl.DlsPackageImpl#getColorSensor()
     * @generated
     */
    EClass COLOR_SENSOR = eINSTANCE.getColorSensor();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_SENSOR__KEY = eINSTANCE.getColorSensor_Key();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.impl.TouchSensorImpl <em>Touch Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.impl.TouchSensorImpl
     * @see robot.ev3.dls.impl.DlsPackageImpl#getTouchSensor()
     * @generated
     */
    EClass TOUCH_SENSOR = eINSTANCE.getTouchSensor();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOUCH_SENSOR__KEY = eINSTANCE.getTouchSensor_Key();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.impl.UltrasonicSensorImpl <em>Ultrasonic Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.impl.UltrasonicSensorImpl
     * @see robot.ev3.dls.impl.DlsPackageImpl#getUltrasonicSensor()
     * @generated
     */
    EClass ULTRASONIC_SENSOR = eINSTANCE.getUltrasonicSensor();

    /**
     * The meta object literal for the '<em><b>Comparator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ULTRASONIC_SENSOR__COMPARATOR = eINSTANCE.getUltrasonicSensor_Comparator();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ULTRASONIC_SENSOR__DISTANCE = eINSTANCE.getUltrasonicSensor_Distance();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.TouchSensorSides <em>Touch Sensor Sides</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.TouchSensorSides
     * @see robot.ev3.dls.impl.DlsPackageImpl#getTouchSensorSides()
     * @generated
     */
    EEnum TOUCH_SENSOR_SIDES = eINSTANCE.getTouchSensorSides();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.Actions <em>Actions</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.Actions
     * @see robot.ev3.dls.impl.DlsPackageImpl#getActions()
     * @generated
     */
    EEnum ACTIONS = eINSTANCE.getActions();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.Directions <em>Directions</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.Directions
     * @see robot.ev3.dls.impl.DlsPackageImpl#getDirections()
     * @generated
     */
    EEnum DIRECTIONS = eINSTANCE.getDirections();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.Colors <em>Colors</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.Colors
     * @see robot.ev3.dls.impl.DlsPackageImpl#getColors()
     * @generated
     */
    EEnum COLORS = eINSTANCE.getColors();

    /**
     * The meta object literal for the '{@link robot.ev3.dls.CompareOperator <em>Compare Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.ev3.dls.CompareOperator
     * @see robot.ev3.dls.impl.DlsPackageImpl#getCompareOperator()
     * @generated
     */
    EEnum COMPARE_OPERATOR = eINSTANCE.getCompareOperator();

  }

} //DlsPackage
