/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Bin Op</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.ev3.dls.ExpressionBinOp#getLeft <em>Left</em>}</li>
 *   <li>{@link robot.ev3.dls.ExpressionBinOp#getBop <em>Bop</em>}</li>
 *   <li>{@link robot.ev3.dls.ExpressionBinOp#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see robot.ev3.dls.DlsPackage#getExpressionBinOp()
 * @model
 * @generated
 */
public interface ExpressionBinOp extends BooleanExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(BooleanExpression)
   * @see robot.ev3.dls.DlsPackage#getExpressionBinOp_Left()
   * @model containment="true"
   * @generated
   */
  BooleanExpression getLeft();

  /**
   * Sets the value of the '{@link robot.ev3.dls.ExpressionBinOp#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(BooleanExpression value);

  /**
   * Returns the value of the '<em><b>Bop</b></em>' attribute.
   * The literals are from the enumeration {@link robot.ev3.dls.BinaryBooleanOperator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bop</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bop</em>' attribute.
   * @see robot.ev3.dls.BinaryBooleanOperator
   * @see #setBop(BinaryBooleanOperator)
   * @see robot.ev3.dls.DlsPackage#getExpressionBinOp_Bop()
   * @model
   * @generated
   */
  BinaryBooleanOperator getBop();

  /**
   * Sets the value of the '{@link robot.ev3.dls.ExpressionBinOp#getBop <em>Bop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bop</em>' attribute.
   * @see robot.ev3.dls.BinaryBooleanOperator
   * @see #getBop()
   * @generated
   */
  void setBop(BinaryBooleanOperator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(BooleanExpression)
   * @see robot.ev3.dls.DlsPackage#getExpressionBinOp_Right()
   * @model containment="true"
   * @generated
   */
  BooleanExpression getRight();

  /**
   * Sets the value of the '{@link robot.ev3.dls.ExpressionBinOp#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(BooleanExpression value);

} // ExpressionBinOp
