/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Constant Int</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.ev3.dls.ExpressionConstantInt#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see robot.ev3.dls.DlsPackage#getExpressionConstantInt()
 * @model
 * @generated
 */
public interface ExpressionConstantInt extends IntExpression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see robot.ev3.dls.DlsPackage#getExpressionConstantInt_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link robot.ev3.dls.ExpressionConstantInt#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // ExpressionConstantInt
