/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see robot.ev3.dls.DlsPackage#getIntExpression()
 * @model
 * @generated
 */
public interface IntExpression extends EObject
{
} // IntExpression
