/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mission</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.ev3.dls.Mission#getBehaviorList <em>Behavior List</em>}</li>
 * </ul>
 *
 * @see robot.ev3.dls.DlsPackage#getMission()
 * @model
 * @generated
 */
public interface Mission extends EObject
{
  /**
   * Returns the value of the '<em><b>Behavior List</b></em>' containment reference list.
   * The list contents are of type {@link robot.ev3.dls.Behavior}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Behavior List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behavior List</em>' containment reference list.
   * @see robot.ev3.dls.DlsPackage#getMission_BehaviorList()
   * @model containment="true"
   * @generated
   */
  EList<Behavior> getBehaviorList();

} // Mission
