/**
 * generated by Xtext 2.10.0
 */
package robot.ev3.dls;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Take Control</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.ev3.dls.TakeControl#getTakecontrol <em>Takecontrol</em>}</li>
 * </ul>
 *
 * @see robot.ev3.dls.DlsPackage#getTakeControl()
 * @model
 * @generated
 */
public interface TakeControl extends EObject
{
  /**
   * Returns the value of the '<em><b>Takecontrol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Takecontrol</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Takecontrol</em>' containment reference.
   * @see #setTakecontrol(BooleanExpression)
   * @see robot.ev3.dls.DlsPackage#getTakeControl_Takecontrol()
   * @model containment="true"
   * @generated
   */
  BooleanExpression getTakecontrol();

  /**
   * Sets the value of the '{@link robot.ev3.dls.TakeControl#getTakecontrol <em>Takecontrol</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Takecontrol</em>' containment reference.
   * @see #getTakecontrol()
   * @generated
   */
  void setTakecontrol(BooleanExpression value);

} // TakeControl
