/**
 * generated by Xtext 2.10.0
 */
package robot.ev3;

import robot.ev3.DslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslStandaloneSetup extends DslStandaloneSetupGenerated {
  public static void doSetup() {
    DslStandaloneSetup _dslStandaloneSetup = new DslStandaloneSetup();
    _dslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
